version: '3.4'

services:
  tournage-frontend:
    image: tournage-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 3000:80
